---
title: '**CENTRO DE HIDROGÊNIO VERDE**'
subtitle: '**Análise Bibliométrica**'
author: '**Victor Valerio**'
date: '**`r format(Sys.Date(), "%d-%m-%Y")`**'
output:
  rmdformats::downcute:
    self_contained: true
    default_style: 'dark'
    downcute_theme: 'default'
---

```{r importacao_dados, results = 'hide', echo = F, warning = F, message = F, error = F}

# Carregando Pacotes Necessários:
library(bibliometrix)
library(magrittr)
library(ggplot2)

# Importação dos Dados (Web of Science):
dados_wos <- convert2df(
  file = list.files(path = '../dados', pattern = 'wos', full.names = TRUE),
  dbsource = 'wos',
  format = 'plaintext')

# Importação dos Dados (Scopus):
dados_scopus <- convert2df(
  file = list.files(path = '../dados', pattern = 'scopus', full.names = TRUE),
  dbsource = 'scopus',
  format = 'bibtex')

# Consolidação dos Dados (Web of Science e Scopus)
consolidado <- mergeDbSources(dados_wos,
                               dados_scopus,
                               remove.duplicated = TRUE)

consolidado <- consolidado %>% 
  dplyr::filter(LA == 'ENGLISH',
                DT == 'ARTICLE')

consolidado_2021 <- consolidado %>% 
  dplyr::filter(LA == 'ENGLISH',
                DT == 'ARTICLE',
                PY <= 2021)

# Calculando Indicadores Bibliométricos:
resultado <- biblioAnalysis(consolidado)

# Cálculo dos Indicadores Bibliométricos Base:
sumario <- summary(resultado, k = 10, pause = F)

# LCdata <- bibliometrix::localCitations(M, fast.search = FALSE, sep = ';')
# histResults <- bibliometrix::histNetwork(M, min.citations = 10, sep = ";")
```

# AMOSTRA DE ARTIGOS CIENTÍFICOS

```{r tabela_amostra, results = 'markup', echo = F, warning = F, message = F, error = F, fig.align ='center'}

# Formação da Tabela com Principais Informações:
tabela_amostra <- sumario %>% 
  purrr::pluck('MainInformationDF') %>% 
  tibble::as_tibble() %>% 
  dplyr::rename('INDICADOR' = Description,
                'VALOR' = Results) %>%   
  dplyr::filter(!INDICADOR %in% c('MAIN INFORMATION ABOUT DATA',
                                  'DOCUMENT TYPES',
                                  'article',
                                  'DOCUMENT CONTENTS',
                                  'AUTHORS',
                                  'AUTHORS COLLABORATION',
                                  'Co-Authors per Documents')) %>% 
  dplyr::slice(1:17) 

# Gerando as Tabelas:
knitr::kable(tabela_amostra)

```

# ANÁLISE DOS TEMAS

```{r mapa_tematico, results = 'markup', echo = F, warning = F, message = F, error = F, fig.align ='center'}

# Montando o Mapa Temático:
mapa_tematico <- thematicMap(consolidado,
                             field = 'DE', 
                             n = 250, 
                             minfreq = 5,
                             stemming = FALSE, 
                             size = 0.5,
                             n.labels = 3, 
                             repel = TRUE) 

mapa_tematico <- mapa_tematico$map 

# Gerando o Gráfico:
plotly::ggplotly(mapa_tematico)

```

# CRESCIMENTO DOS TEMAS

```{r crescimento_temas, results = 'markup', echo = F, warning = F, message = F, error = F, fig.align ='center'}

# Montando O Crescimento dos Temas:
dinamica_palavras <- KeywordGrowth(consolidado_2021, 
                              Tag = 'DE', 
                              sep = ";", 
                              top = 10, 
                              cdf = TRUE)

colnames(dinamica_palavras) <- stringr::str_to_lower(colnames(dinamica_palavras))

# Gerando o Gráfico:
dinamica_palavras_graf <- dinamica_palavras %>% 
  tidyr::pivot_longer(!(year), names_to = 'Words', values_to = 'Occurrences') %>% 
  dplyr::rename('Year' = year) %>% 
  ggplot(mapping = aes(x = Year, y = Occurrences, color = Words)) + 
  geom_line(size = 0.6) +
  geom_point(size = 1) +
  labs(color = '',
       x = 'Years',
       y = 'Annual Occurrences')

plotly::ggplotly(dinamica_palavras_graf) %>% 
  plotly::layout(legend = list(orientation = 'h', x = 0, y =-0.2))

```

# PRODUTIVIDADE DOS AUTORES

```{r}

# Geração de Dados de Produtividade dos Autores:
curva_lotka <- lotka(resultado)

curva_lotka_observada <- tibble::as_tibble(curva_lotka[["AuthorProd"]]) %>% 
  dplyr::rename('Articles' = N.Articles,
                'Authors' = N.Authors,
                'Observed' = Freq)

curva_lotka_teorica <- tibble::as_tibble(10^(log10(curva_lotka$C)-2*log10(curva_lotka$AuthorProd[,1]))) %>% 
  dplyr::rename('Theoretical' = value)


lotka_consolidado <- cbind(curva_lotka_observada, 
                           curva_lotka_teorica) %>% 
  dplyr::mutate(Observed = round(as.numeric(Observed), 4),
                Theoretical = round(as.numeric(Theoretical), 4)) %>% 
  dplyr::select(!Authors) %>% 
  tidyr::pivot_longer(-Articles,
                      names_to = 'Type',
                      values_to = 'Value')


# Gerando Gráfico de Produtividade dos Autores:
grafico_lotka <- lotka_consolidado %>% 
  ggplot(mapping = aes(x = Articles, y = Value, color = Type)) + 
  geom_line(size = 0.5) +
  geom_point(size = 1.5) +
  labs(color = '', 
       x = 'Articles', 
       y = 'Freq. of Authors') + 
  theme(legend.position = 'bottom')

grafico_lotka
# Beta coefficient estimate
#L$Beta
# Constant
#L$C
# Goodness of fit
#L$R2
# P-value of K-S two sample test
#L$p.value
```




